#!/bin/bash

set -x
set -e

# FFS
LLVMV=14.0.0

STAGE0=../build-full
CC=$STAGE0/bin/clang
CXX=$STAGE0/bin/clang++

DEST=./lib/clang/${LLVMV}/lib
rm -rf ${DEST}
mkdir -p ${DEST}

cmake \
	-DCMAKE_C_COMPILER=$CC \
	-DCMAKE_C_COMPILER_TARGET=$target \
	-DCMAKE_C_COMPILER_WORKS=YES \
	-DLLVM_TARGETS_TO_BUILD=Mips \
	-DLLVM_TARGET_ARCH=Mips \
	-DLLVM_DEFAULT_TARGET_TRIPLE=$target \
	-DLLVM_RUNTIMES_TARGET=$target \
	-DCOMPILER_RT_DEFAULT_TARGET_TRIPLE=mips64-sgi-irix6.5 \
	-DLLVM_ENABLE_RUNTIMES="compiler-rt" \
	-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
	-DCOMPILER_RT_BUILD_BUILTINS=ON \
	-DCOMPILER_RT_BUILD_CRT=ON \
	-DCOMPILER_RT_CRT_USE_EH_FRAME_REGISTRY=ON \
	-DCOMPILER_RT_BUILD_SANITIZERS=OFF \
	-DCOMPILER_RT_BUILD_XRAY=OFF \
	-DCOMPILER_RT_BUILD_XRAY_NO_PREINIT=OFF \
	-DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
	-DCOMPILER_RT_BUILD_PROFILE=OFF \
	-DCOMPILER_RT_BUILD_MEMPROF=OFF \
	-DCMAKE_BUILD_TYPE=Release \
	-DCAN_TARGET_mips64=YES \
	-DCAN_TARGET_mipsn32=YES \
	-GNinja \
	../runtimes
ninja

cp -r compiler-rt/lib/mips64* $DEST

